// @ts-check
// 가이드는 세 영역으로 나눈다. 상단 메뉴의 이용 가이드·제작 가이드·도움말이 각 사이드바의 첫 문서로 간다.
// - useSidebar: 서비스를 이용하는 사람(접속·계정·대화·결제)
// - createSidebar: 작품을 만드는 사람(작품 만들기, 구버전 제작 방식, 크리에이터)
// - helpSidebar: 문제 해결과 정책
// 분류 이름과 순서는 여기서 정하고, 분류 안 문서 순서는 각 문서의 sidebar_position 으로 정한다.
// 분류 이름을 바꾸면 i18n/<locale>/docusaurus-plugin-content-docs/current.json 의 키도 같이 바꾼다.
// 첫 화면(intro.md)과 예전 주소 안내용 숨김 문서(unlisted)는 어느 사이드바에도 넣지 않는다.

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  useSidebar: [
    {type: 'category', label: 'MYMI 시작하기', collapsed: false, items: [{type: 'autogenerated', dirName: 'getting-started'}]},
    {type: 'category', label: '계정', items: [{type: 'autogenerated', dirName: 'account'}]},
    {type: 'category', label: '대화하기', items: [{type: 'autogenerated', dirName: 'chatting'}]},
    {type: 'category', label: '스파크와 결제', items: [{type: 'autogenerated', dirName: 'payment'}]},
  ],
  createSidebar: [
    {type: 'category', label: '작품 만들기', collapsed: false, items: [{type: 'autogenerated', dirName: 'create/making'}]},
    {type: 'category', label: '구버전 제작 방식(1.0)', items: [{type: 'autogenerated', dirName: 'create/legacy'}]},
    {type: 'category', label: '크리에이터', items: ['creator-support/support']},
  ],
  helpSidebar: [
    {type: 'category', label: '자주 묻는 질문', collapsed: false, items: ['faq/faq', 'faq/cookie-clear']},
    {type: 'category', label: '약관과 정책', items: ['policy/terms']},
  ],
};

export default sidebars;
